config/routes.rb
Rails.application.routes.draw do
  scope module: :web do
    root to: 'shorters#new'
    get '/docs', to: 'static#docs'
    resources :shorters, only: %i[create show edit], path: '', param: :code do
      resources :visitors, only: %i[create]
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :shorters, only: %i[index show create], param: :code
    resources :visitors, only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shorter.rb
# Cm
class Shorter < ApplicationRecord
  has_many :visitors, dependent: :destroy
  validates :original_url, presence: true
  validates :original_url, format: %r{\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,63}(:[0-9]{1,5})?(\/.*)?\z}ix
  before_create :generate_data

  def check_for_duplicates
    Shorter.find_by(purified_url: purifying)
  end

  def purifying
    original_url.downcase.gsub(%r{(https?:\/\/)|(http?:\/\/)|(www\.)}, '')
  end

  def tracking(data)
    country = data.country || 'unknown'
    visitors.create(ip: data.ip, country: country)
  end

  private

    def generate_data
      self.purified_url = purifying
      self.code = SecureRandom.base58(6)
      generate_data if Shorter.exists?(code: code)
    end
end

app/models/visitor.rb
# Cm
class Visitor < ApplicationRecord
  belongs_to :shorter
  validates :ip, presence: true
  validates :country, presence: true
end

app/controllers/api/shorters_controller.rb
module Api
  # Cm
  class ShortersController < ActionController::API
    include Response
    include ExceptionHandler

    def index
      @shorters = Shorter.all
      json_response(@shorters)
    end

    def create
      duplicate = Shorter.new(shorter_params).check_for_duplicates
      return json_response(duplicate, :created) if duplicate.present?

      @shorter = Shorter.create!(shorter_params)
      json_response(@shorter, :created)
    end

    def show
      @shorter = Shorter.find_by!(code: params[:code])
      json_response(@shorter)
    end

    private

      def shorter_params
        params.require(:shorter).permit(:original_url)
      end
  end
end

app/controllers/api/visitors_controller.rb
module Api
  # Cm
  class VisitorsController < ActionController::API
    include Response
    include ExceptionHandler

    def index
      @visitors = Visitor.all
      json_response(@visitors)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/exception_handler.rb
# Cm
module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      json_response({ message: e.message }, :not_found)
    end

    rescue_from ActiveRecord::RecordInvalid do |e|
      json_response({ message: e.message }, :unprocessable_entity)
    end
  end
end

app/controllers/concerns/response.rb
# Cm
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/web/shorters_controller.rb
module Web
  # Cm
  class ShortersController < ApplicationController
    require 'geocoder'

    def new
      @shorter = Shorter.new
    end

    def create
      shorter = Shorter.new(shorter_params)
      duplicate = shorter.check_for_duplicates
      return render template: 'web/shorters/edit', locals: { shorter: duplicate } if duplicate.present?

      if shorter.save
        render template: 'web/shorters/edit', locals: { shorter: shorter }
      else
        redirect_to root_path, flash: { error: t('.error') }
      end
    end

    def show
      @shorter = Shorter.find_by(code: params[:code])
      return redirect_to root_path unless @shorter

      @shorter.tracking(request.location)
      redirect_to @shorter.original_url, status: :moved_permanently
    end

    def edit; end

    private

      def shorter_params
        params.require(:shorter).permit(:original_url)
      end
  end
end

app/controllers/web/static_controller.rb
module Web
  # Cm
  class StaticController < ApplicationController
    def docs; end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang='en')
  %head
    %meta(charset='utf-8')
    %meta(http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1')
    %meta(name='viewport' content='width=device-width, initial-scale=1.0')
    %title= content_for?(:title) ? yield(:title) : 'Ark::Shorter'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js'

  %body

    %nav.navbar.navbar-default
      .container
        .col-md-6.col-xs-12
          = link_to image_tag('logo.svg', height: 35), root_path, class: 'navbar-brand'
        .col-md-6.hidden-xs
          %ul.nav.navbar-nav.navbar-right
            %li
              = link_to '[ api_doc ]', docs_path, class: 'btn-navbar'
            %li
              = link_to '[ source ]', 'https://github.com/TeralGoe/ark_shorter', class: 'btn-navbar', target: '_blank'

    .container
      .row
        .col-xs-12
          = yield
  = yield :js_view

app/views/web/shorters/edit.html.haml
- content_for :js_view do
  :javascript
    var clipboard = new ClipboardJS('.form-button');

.container-fluid.shorter-box
  .row
    .col-md-10.col-xs-9.no-paddings
      = text_field_tag 'shorter', "#{request.base_url}/#{shorter.code}", class: 'form-input'
    .col-md-2.col-xs-3.no-paddings.right
      = submit_tag '[ copy ]', class: 'form-button', data: { 'clipboard-action': 'copy', 'clipboard-target': '#shorter' }

  .shorter-info
    &mdash; Your link is shortened: 
    = link_to '[ visit ]', "#{request.base_url}/#{shorter.code}", target: '_blank'

app/views/web/shorters/new.html.haml
.container-fluid.shorter-box
  .row
    = form_for @shorter, url: shorters_path do |f|
      .col-md-10.col-xs-9.no-paddings
        = f.text_field :original_url, class: 'form-input', placeholder: 'Paste URL here'
      .col-md-2.col-xs-3.no-paddings.right
        = f.button '[ shorten ]', class: 'form-button'

- if flash[:error].present?
  .shorter-info
    &mdash;
    = raw flash[:error]